server:
  servlet:
    context-path: '${APPLICATION_CONTEXT_PATH:/EventWebApp}'
  port: '${APPLICATION_PORT:8095}'

spring:
  profiles:
    active: '${SPRING_ACTIVE_PROFILE:eventPersistorFeignClient}'

feign:
  client:
    config:
      event-persistor:
        name: '${EVENT_PERSISTOR_CLIENT_NAME:event-persistor}'
        url: '${EVENT_PERSISTOR_CLIENT_URL:localhost:8082}'
        context-path: '${EVENT_PERSISTOR_CLIENT_CONTEXT_PATH:/EventPersistor}'
        connectTimeout: '${EVENT_PERSISTOR_CLIENT_CONNECT_TIMEOUT:3000}'
        readTimeout: '${EVENT_PERSISTOR_CLIENT_READ_TIMEOUT:3000}'