server:
  servlet:
    context-path: '/EventPersistor'
  port: '8082'

spring:
  data:
    mongodb:
      host: 'localhost'
      port: '27018'
      database: 'event_radar'
      username: 'root'
      password: 'root'
      authentication-database: 'admin'
      connection-timeout: '3000'
      socket-timeout: '10000'
      max-wait-time: '3000'
      server-selection-timeout: '3000'
  rabbitmq:
    host: 'localhost'
    port: '5673'
    username: 'rabbitmq_user'
    password: 'rabbitmq_password'
    reply-timeout: '5000'

queue:
  single-queue: 'singleQueue'

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: 'DEBUG'