server:
  servlet:
    context-path: '${APPLICATION_CONTEXT_PATH:/EventPersistor}'
  port: '${APPLICATION_PORT:8082}'

spring:
  data:
    mongodb:
      host: '${MONGODB_HOST:localhost}'
      port: '${MONGODB_PORT:27018}'
      database: '${MONGODB_DATABASE:event_radar}'
      username: '${MONGODB_USERNAME:root}'
      password: '${MONGODB_PASSWORD:root}'
      authentication-database: '${MONGODB_AUTHENTICATION_DATABASE:admin}'
      connection-timeout: '${MONGODB_CONNECTION_TIMEOUT:3000}'
      socket-timeout: '${MONGODB_SOCKET_TIMEOUT:10000}'
      max-wait-time: '${MONGODB_MAX_WAIT_TIME:3000}'
      server-selection-timeout: '${MONGODB_SERVER_SELECTION_TIMEOUT:3000}'

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: '${MONGO_TEMPLATE_LOGGING:DEBUG}'