services:
  application:
    image: 'peachex/event-manager-application:latest'
    container_name: 'event-manager-application'
    environment:
      - 'APPLICATION_PORT=8090'
      - 'SPRING_ACTIVE_PROFILE=eventPersistorFeignClient'
      - 'APPLICATION_CONTEXT_PATH=/EventManager'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USERNAME=rabbitmq_user'
      - 'RABBITMQ_PASSWORD=rabbitmq_password'
      - 'QUEUE_TASK_SCHEDULER=task-scheduler-queue'
      - 'EVENT_PERSISTOR_CLIENT_NAME=event-persistor'
      - 'EVENT_PERSISTOR_CLIENT_URL=event-persistor-application:8082'
      - 'EVENT_PERSISTOR_CLIENT_CONTEXT_PATH=/EventPersistor'
      - 'EVENT_PERSISTOR_CLIENT_CONNECT_TIMEOUT=3000'
      - 'EVENT_PERSISTOR_CLIENT_READ_TIMEOUT=3000'
    ports:
      - '8091:8090'
    restart: 'on-failure'
    networks:
      - 'eventradar-network'

networks:
  eventradar-network:
    driver: 'bridge'
    name: 'eventradar-network'