services:
  postgres:
    image: postgres
    container_name: 'pg-database'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=task_scheduler'
    ports:
      - '5433:5432'
    restart: 'on-failure'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      - './db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - 'eventradar-network'

volumes:
  postgres-data:
    driver: 'local'

networks:
  eventradar-network:
    driver: 'bridge'
    name: 'eventradar-network'