services:
  postgres:
    image: postgres
    container_name: 'pg-database'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=task_scheduler'
    ports:
      - '5433:5432'
    restart: 'on-failure'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      - './db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - 'eventradar-network'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5673:5672"     # RabbitMQ main port
      - "15673:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq_user'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq_password'
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'
    networks:
      - 'eventradar-network'

volumes:
  postgres-data:
    driver: 'local'

  rabbitmq-data:
    driver: 'local'

networks:
  eventradar-network:
    driver: 'bridge'
    name: 'eventradar-network'