version: '3'

services:
  mongodb:
    image: mongo
    container_name: 'mongo-db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
    ports:
      - '27018:27017'
    restart: 'on-failure'
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - 'eventradar-network'

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: 'on-failure'
    ports:
      - '27019:8081'
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=root'
      - 'ME_CONFIG_BASICAUTH_USERNAME=admin'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=admin'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
    networks:
      - 'eventradar-network'

volumes:
  mongo-data:
    driver: 'local'

networks:
  eventradar-network:
    driver: 'bridge'