version: '3'

services:
  event-persistor:
    build: ./
    container_name: 'event-persistor-application'
    environment:
      - 'APPLICATION_PORT=8082'
      - 'APPLICATION_CONTEXT_PATH=/EventPersistor'
      - 'MONGODB_HOST=mongodb'
      - 'MONGODB_PORT=27017'
      - 'MONGODB_DATABASE=event_radar'
      - 'MONGODB_USERNAME=root'
      - 'MONGODB_PASSWORD=root'
      - 'MONGODB_AUTHENTICATION_DATABASE=admin'
      - 'MONGODB_CONNECTION_TIMEOUT=3000'
      - 'MONGODB_SOCKET_TIMEOUT=10000'
      - 'MONGODB_MAX_WAIT_TIME=3000'
      - 'MONGODB_SERVER_SELECTION_TIMEOUT=3000'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USERNAME=rabbitmq_user'
      - 'RABBITMQ_PASSWORD=rabbitmq_password'
      - 'RABBITMQ_REPLY_TIMEOUT=5000'
      - 'QUEUE_SINGLE_QUEUE=singleQueue'
      - 'MONGO_TEMPLATE_LOGGING=DEBUG'
    ports:
      - '8083:8082'
    restart: 'on-failure'
    networks:
      - 'eventradar-network'

  mongodb:
    image: mongo
    container_name: 'mongo-db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
    ports:
      - '27018:27017'
    restart: 'on-failure'
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - 'eventradar-network'

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: 'on-failure'
    ports:
      - '27019:8081'
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=root'
      - 'ME_CONFIG_BASICAUTH_USERNAME=mongo_express_user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=mongo_express_password'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
    networks:
      - 'eventradar-network'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5673:5672"     # RabbitMQ main port
      - "15673:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq_user'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq_password'
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'
    networks:
      - 'eventradar-network'

volumes:
  mongo-data:
    driver: 'local'

  rabbitmq-data:
    driver: 'local'

networks:
  eventradar-network:
    driver: 'bridge'