server:
  servlet:
    context-path: '${APPLICATION_CONTEXT_PATH:/SyncTaskScheduler}'
  port: '${APPLICATION_PORT:8088}'

spring:
  datasource:
    url: '${POSTGRES_HOST:jdbc:postgresql://localhost:5433/sync_task_scheduler}'
    database: '${DATABASE:sync_task_scheduler}'
    username: '${POSTGRES_USERNAME:postgres}'
    password: '${POSTGRES_PASSWORD:postgres}'
    driver-class-name: '${DRIVER_CLASS_NAME:org.postgresql.Driver}'

    hikari:
      connection-timeout: '${HIKARI_CONNECTION_TIMEOUT:3000}'
      maximum-pool-size: '${HIKARI_MAXIMUM_POOL_SIZE:10}'
      minimum-idle: '${HIKARI_MINIMUM_IDLE:5}'
      idle-timeout: '${HIKARI_IDLE_TIMEOUT:600000}'
      max-lifetime: '${HIKARI_MAX_LIFETIME:1800000}'
      validation-timeout: '${HIKARI_VALIDATION_TIMEOUT:3000}'
      leak-detection-threshold: '${HIKARI_LEAK_DETECTION_THRESHOLD:15000}'
      pool-name: '${HIKARI_POOL_NAME:SyncTaskScheduler-HikariPool}'

  jpa:
    hibernate:
      ddl-auto: '${JPA_HIBERNATE_DDL_AUTO:update}'
    show-sql: '${JPA_HIBERNATE_SHOW_SQL:true}'

  rabbitmq:
    host: '${RABBITMQ_HOST:localhost}'
    port: '${RABBITMQ_PORT:5673}'
    username: '${RABBITMQ_USERNAME:rabbitmq_user}'
    password: '${RABBITMQ_PASSWORD:rabbitmq_password}'

queue:
  task-scheduler: '${TASK_SCHEDULER_QUEUE:task-scheduler-queue}'