server:
  servlet:
    context-path: '${APPLICATION_CONTEXT_PATH:/EventManger}'
  port: '${APPLICATION_PORT:8090}'

spring:
  rabbitmq:
    host: '${RABBITMQ_HOST:localhost}'
    port: '${RABBITMQ_PORT:5673}'
    username: '${RABBITMQ_USERNAME:rabbitmq_user}'
    password: '${RABBITMQ_PASSWORD:rabbitmq_password}'

queue:
  task-scheduler: '${TASK_SCHEDULER_QUEUE:task-scheduler-queue}'

feign:
  client:
    config:
      event-persistor:
        name: '${EVENT_PERSISTOR_CLIENT_NAME:event-persistor}'
        url: '${EVENT_PERSISTOR_CLIENT_URL:localhost:8083}'
        context-path: '${EVENT_PERSISTOR_CLIENT_CONTEXT_PATH:/EventPersistor}'
        connectTimeout: '${EVENT_PERSISTOR_CLIENT_CONNECT_TIMEOUT:3000}'
        readTimeout: '${EVENT_PERSISTOR_CLIENT_READ_TIMEOUT:11000}'
        errorDecoder: by.klevitov.eventmanager.manager.client.EventPersistorClientErrorDecoder
        # retryer: com.example.SimpleRetryer
        # decode404: false